# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy Backend (Docker)

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: calpcb-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1. checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. setup buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. login to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. build & push image
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/sukumaporn2546/calpcb-backend:latest
            ghcr.io/sukumaporn2546/calpcb-backend:${{ github.sha }}

      # 5. copy docker-compose to VM
      - name: Upload docker-compose to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "./docker-compose.yml"
          target: "~/backend-app"

      # 6. deploy on VM
      - name: Deploy Backend on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/backend-app

            # login to GHCR
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

            # write .env on server (NO SECRETS inside GitHub repo)
            cat > .env << EOF
            USER=${{ secrets.USER }}
            PASSWORD=${{ secrets.PASSWORD }}
            HOST=${{ secrets.HOST }}
            DBNAME=${{ secrets.DBNAME}}
            PORT=${{ secrets.PORT }}
            EOF

            # deploy
            docker compose pull
            docker compose up -d --remove-orphans

            docker image prune -af --filter "until=24h"

            echo "ðŸš€ Backend deployed successfully!"

